export const RESPONSE_STATUS_SUCCESS = 200;
export const RESPONSE_STATUS_CREATED = 201;
export const RESPONSE_STATUS_BAD_REQUEST = 400;
export const RESPONSE_STATUS_UNAUTHORIZED = 401;
export const RESPONSE_STATUS_FORBIDDEN = 403;
export const RESPONSE_STATUS_NOT_FOUND = 404;
export const RESPONSE_STATUS_SERVER_ERROR = 500;
